M48
; DRILL file {KiCad 9.0.0} date 2025-04-06T00:07:15-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-04-06T00:07:15-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0512
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1181
%
G90
G05
T1
X6.4118Y-4.626
X6.4118Y-4.9803
T2
X5.8287Y-3.037
T3
X5.4293Y-3.0266
X5.4293Y-5.3022
X6.327Y-3.0266
X6.327Y-5.3022
M30
